app/ticket/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, TextField, RadioField, TextAreaField, SelectField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo, Length

ticket_app = ([
    ( '1', 'Server' ),
    ( '2', 'Local App' )
    ])

ticket_arg = ([
    ( '1', 'Development (code)' ),
    ( '2', 'Deploy (code)' ),
    ( '3', 'Bugs (code)' ),
    ( '4', 'ACMG criteria (variant)' ),
    ( '5', 'Bugs (front-end)' ),
    ( '6', 'Improvement Suggestion' ),
    ( '7', 'Other' )
    ])

urgency_choices = ([
    ( '1', 'Low' ),
    ( '2', 'Medium' ),
    ( '3', 'High' )
    ])

class TicketForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(min=1, max=250)])
    body = TextAreaField('Body', validators=[DataRequired(), Length(min=1, max=4000)])
    urgency = RadioField('Urgency', choices=urgency_choices, validators=[DataRequired()] )
    application = RadioField('Application', choices=ticket_app, validators=[DataRequired()])
    argument = SelectField('Argument', choices=ticket_arg, validators=[DataRequired()])
    submit = SubmitField('Submit')

class TicketReplyForm(FlaskForm):
    body = TextAreaField('Update')
    follow = BooleanField('Follow Ticket Updates (e-mail)')
    submit = SubmitField('Update')

app/ticket/__init__.py
from flask import Blueprint

bp = Blueprint('ticket', __name__)

from app.ticket import routes

app/ticket/routes.py
from app.ticket import bp
from app import db
from flask import flash, url_for, redirect
from flask import render_template, current_app, send_from_directory
from flask_login import login_user, logout_user, current_user, login_required
from app.decorators import check_confirmed
from datetime import datetime
import os
from app.models import User, Ticket, TicketReply
from app.ticket.forms import TicketForm, TicketReplyForm
from app.ticket.forms import ticket_app, ticket_arg, urgency_choices
from app.ticket.email import send_ticket_email, send_ticket_closure_email, send_ticket_reopen_email

@bp.route('/index')
@login_required
def index():
    return( render_template( 'ticket/index.html' ))

@bp.route('/all')
@login_required
def all():
    tickets = Ticket.query.all()
    return( render_template( 'ticket/all.html',
                ticket_app = dict(ticket_app),
                ticket_arg = dict(ticket_arg),
                urgency_choices = dict(urgency_choices),
                tickets=tickets ))


@bp.route('/user/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    tickets = user.tickets.all()
    ticket_replies = user.ticket_replies.all()
    tickets_followed = user.tickets_followed
    return( render_template( 'ticket/user.html',
                                ticket_app = dict(ticket_app),
                                ticket_arg = dict(ticket_arg),
                                urgency_choices = dict(urgency_choices),
                                user=user,
                                tickets=tickets,
                                ticket_replies=ticket_replies,
                                tickets_followed=tickets_followed
                            ))

@bp.route('/submit', methods=['GET', 'POST'])
@login_required
def submit():
    form = TicketForm()
    if form.validate_on_submit():
        ticket = Ticket(
            author = current_user,
            urgency = form.urgency.data,
            application = form.application.data,
            argument = form.argument.data,
            title = form.title.data,
            body = form.body.data
        )
        db.session.add(ticket)
        db.session.commit()
        flash('Ticket submitted!', 'success')
        return( redirect( url_for('ticket.ticket_reply', ticket_ID = ticket.id )))
    return( render_template( 'ticket/ticket_submit.html', form=form ))


@bp.route('/ticket_reply/<ticket_ID>', methods=['GET', 'POST'])
@login_required
def ticket_reply(ticket_ID):
    user = User.query.filter_by(username=current_user.username).first_or_404()
    ticket = Ticket.query.filter_by(id=ticket_ID).first_or_404()
    ticket_replies = ticket.ticket_replies.all()
    form = TicketReplyForm()
    if form.validate_on_submit():
        follow = form.follow.data
        body = form.body.data
        if follow:
            ticket.ticket_followers.append(user)
        if body:
            ticket_reply = TicketReply(
                replier = current_user,
                original = ticket,
                body = body
                )
            ticket.last_modify = datetime.utcnow()
            ticket.ticket_followers.append(user)
            send_ticket_email(ticket.author, ticket_reply)
            for single_user in ticket.ticket_followers:
                send_ticket_email(single_user, ticket_reply)
            db.session.add(ticket_reply)
        db.session.commit()
        flash('Ticket updated!', 'success')
        return( redirect( url_for('ticket.ticket_reply', ticket_ID = ticket.id )))
    return( render_template( 'ticket/ticket_reply.html',
                        ticket=ticket,
                        ticket_replies=ticket_replies,
                        ticket_app = dict(ticket_app),
                        ticket_arg = dict(ticket_arg),
                        urgency_choices = dict(urgency_choices),
                        form = form
                        ))

@bp.route('/close/<ticket_ID>')
@login_required
def close(ticket_ID):
    ticket = Ticket.query.filter_by(id=ticket_ID).first_or_404()
    ticket.closed = True
    ticket.closed_on = datetime.utcnow()
    send_ticket_closure_email(ticket.author, ticket)
    for single_user in ticket.ticket_followers:
        send_ticket_closure_email(single_user, ticket)
    db.session.commit()
    return( redirect( url_for('ticket.ticket_reply', ticket_ID = ticket.id )))

@bp.route('/reopen/<ticket_ID>')
@login_required
def reopen(ticket_ID):
    ticket = Ticket.query.filter_by(id=ticket_ID).first_or_404()
    ticket.closed = False
    ticket.last_modify = datetime.utcnow()
    send_ticket_reopen_email(ticket.author, ticket)
    for single_user in ticket.ticket_followers:
        send_ticket_reopen_email(single_user, ticket)
    db.session.commit()
    return( redirect( url_for('ticket.ticket_reply', ticket_ID = ticket.id )))

app/templates/ticket/all.html
{% extends "base_DXcator.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}

<style>
  div.ticket-container {
    font-size: 150%;
  }
  .value {
    font-weight: normal;
    font-family: monospace;
    font-size: 80%;
  }
  stream.key {
    font-weight: bold;
  }
  #larger {
    font-size: 100%;
    font-family: monospace;
  }
  th {
    text-align: center;
    background-color: #dedede;
    vertical-align: middle;
  }
  td {
    font-size: 75%;
    font-family: monospace;
    max-width: 20%;
    overflow-wrap: break-word;
    vertical-align: middle;
  }
  table {
    table-layout:fixed;
    width:100%;
  }
  .closed {
    background-color: rgba(255, 0, 0, 0.15);;
  }
  stream#open {
    color: green;
  }
  stream#closed {
    color: red;
    font-weight: bold;
  }
</style>


  <div style="text-align: center; margin-top: 2%;">
    <a href="{{ url_for('ticket.submit')}}">
    <button class="btn btn-info">Submit your ticket</button>
    </a>
  </div>

  <div class="ticket-container" style="margin-top: 2%;">
  <hr>
  <h3>Tickets:</h3>

    <table class="table table-hover" style="text-align: center;">

      <thead>
        <tr>
          <th>
            author
          </th>
          <th>
            title
          </th>
          <th>
            application
          </th>
          <th>
            topic
          </th>
          <th>
            status
          </th>
          <th>
            created on
          </th>
          <th>
            last update
          </th>
        </tr>
      </thead>

      <tbody>
        {% for ticket in tickets %}

        {% set STATUS = 'open' %}
        {% if ticket.closed %}
          {% set STATUS = 'closed' %}
        {% endif %}

        <tr>
          <td class="{{ STATUS }}">
            <a href="{{ url_for( 'ticket.user', username = ticket.author.username ) }}">
              {{ ticket.author.username }}
            </a>
          </td>
          <td class="{{ STATUS }}">
            <a href="{{ url_for( 'ticket.ticket_reply', ticket_ID = ticket.id ) }}" target="_blank">
              {{ ticket.title }}
            </a>
          </td>
          <td class="{{ STATUS }}">
            {{ ticket_app[ticket.application|string] }}
          </td>
          <td class="{{ STATUS }}">
            {{ ticket_arg[ticket.argument|string] }}
          </td>
          <td class="{{ STATUS }}">
            <stream id="{{ STATUS }}">
              {{ STATUS }}
            </stream>
          </td>
          <td class="{{ STATUS }}">
            {{ ticket.timestamp.strftime("%m-%d-%Y (%H:%M)") }}
          </td>
          <td class="{{ STATUS }}">
            {{ ticket.last_modify.strftime("%m-%d-%Y (%H:%M)") }}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

  </div>


{% endblock %}

app/templates/ticket/blank_DXcator.html
{% extends "base_DXcator.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}



{% endblock %}

app/templates/ticket/index.html
{% extends "base_DXcator.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}

<style>
  div.index-container {
    text-align: center;
    vertical-align: middle;
    margin-top: 25%;
    border: 0px solid red;
  }
</style>

  <div class="index-container">

    <h2>Ticket System</h2>

    <br/>
    <br/>

    <a href="{{ url_for('ticket.submit') }}">
      <button class="btn btn-success">
        Submit New Ticket
      </button>
    </a>

    <br/>
    <br/>

    <a href="{{ url_for('ticket.all') }}">
      <button class="btn btn-info">
        View All Tickets
      </button>
    </a>

    <br/>
    <br/>

    <a href="{{ url_for('ticket.user', username=current_user.username) }}">
      <button class="btn">
        View Your Tickets
      </button>
    </a>
    <br>

  </div>

{% endblock %}

app/templates/ticket/ticket.html
{% extends "base_DXcator.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}

<style>
  stream.key {
    font-weight: bold;
  }
  stream.value {
  }
  div.ticket-container {
    font-size: 150%;
  }
</style>

  <div class="ticket-container" style="margin-top: 15%;">
    <stream class="key">Author:</stream> <stream class="value">{{ ticket.author.username }}</stream>
    <br>
    <stream class="key">Ticket ID:</stream> <stream class="value">{{ ticket.id }}</stream>
    <br>
    <stream class="key">Created On:</stream> <stream class="value">{{ ticket.timestamp }}</stream>
    <br>
    <stream class="key">Last Modified:</stream> <stream class="value">{{ ticket.last_modify }}</stream>
    <br>
    <stream class="key">Ticket Body:</stream>
    <br>
    <stream class="value">{{ ticket.body }}</stream>
    <br>
  </div>

{% endblock %}

app/templates/ticket/ticket_reply.html
{% extends "base_DXcator.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}

<style>
  div.ticket-container {
    font-size: 150%;
  }
  .value {
    font-weight: normal;
    font-family: monospace;
    font-size: 80%;
  }
  stream.key {
    font-weight: bold;
  }
  #larger {
    font-size: 100%;
    font-family: monospace;
  }
  div.ticket-group {
    overflow-wrap: break-word;
  }
  stream#open {
    color: green;
  }
  stream#closed {
    color: red;
    font-weight: bold;
  }
  .closed {
    background-color: rgba(255, 0, 0, 0.2);;
  }
</style>

  {% set STATUS = 'open' %}
  {% if ticket.closed %}
    {% set STATUS = 'closed' %}
  {% endif %}

  <div class="ticket-container {{STATUS}}" style="margin-top: 5%;">

    <stream class="key">Author:</stream> <stream class="value">
      <a href="{{ url_for('ticket.user', username = ticket.author.username ) }}">
        {{ ticket.author.username }}
      </a>
    </stream>
    <br>
    <br>

    <div class="ticket-group">
      <stream class="key">Status: </stream>
      <stream class="value" id="{{ STATUS }}">
        {{ STATUS }}
      </stream>
      {% if current_user == ticket.author or current_user.admin %}
        {% if not ticket.closed %}
          <a href="{{ url_for('ticket.close', ticket_ID = ticket.id ) }}">
            <button class="btn btn-danger" style="margin-left: 60%;">Close Ticket</button>
          </a>
        {% else %}
          <stream class="value" style="font-size: 60%;">
            {{ ticket.closed_on.strftime("%m-%d-%Y (%H:%M)") }}
          </stream>
          <a href="{{ url_for('ticket.reopen', ticket_ID = ticket.id ) }}">
            <button class="btn btn-success" style="margin-left: 60%;">Reopen Ticket</button>
          </a>
        {% endif %}
      {% endif %}
    </div>
    <br>

    <div class="ticket-group">
      <stream class="key">Title: </stream><stream class="value">
        <a href="{{ url_for('ticket.ticket_reply', ticket_ID = ticket.id ) }}">
          {{ ticket.title }}
        </a>
      </stream>
    </div>
    <br>
    <div class="ticket-group">
      <stream class="key">Urgency:</stream>
      <stream class="value">{{ urgency_choices[ticket.urgency|string] }}</stream>
    </div>
    <br>
    <div class="ticket-group">
      <stream class="key">Application:</stream>
      <stream class="value">{{ ticket_app[ticket.application|string] }}</stream>
    </div>
    <br>
    <div class="ticket-group">
      <stream class="key">Argument:</stream>
      <stream class="value">{{ ticket_arg[ticket.argument|string] }}</stream>
    </div>
    <br>
    <div class="ticket-group">
      <stream class="key">Body:</stream>
      <br>
      <div class="ticket_reply-group" style="border: 1px solid #bababa;">
        <stream class="value" style="font-weight: bold;">{{ ticket.author.username }}, {{ticket.timestamp.strftime("%m-%d-%Y (%H:%M)")}}</stream><stream class="value">: {{ ticket.body }}</stream>
      </div>
      {% for ticket_reply in ticket_replies %}
        {% if (loop.index % 2) == 0: %}
          <div class="ticket_reply-group" style="margin-left: {{loop.index}}%; border: 1px solid #bababa; margin-top: 0.5%;">
          {% else %}
            <div class="ticket_reply-group" style="margin-left: {{loop.index}}%; border: 1px solid #dedede; margin-top: 0.5%;">
        {% endif %}
          <stream class="value" style="font-weight: bold;">{{ ticket_reply.replier.username }}, {{ticket_reply.timestamp.strftime("%m-%d-%Y (%H:%M)") }}:</stream>
          <stream class="value">{{ ticket_reply.body }}</stream>
        </div>
      {% endfor %}
    </div>

    {% if not ticket.closed %}

      <br>
      <div class="row">
          <div class="col-md-4">
              {{ wtf.quick_form(form) }}
          </div>
      </div>

      <br>
      <br>
      <div class="ticket-group">
        <stream class="key">Followed By:</stream>
        {% for single_user in ticket.ticket_followers %}
          <br>
          <stream class="value" style="margin-left: 2%;">-
            <a href="{{ url_for('ticket.user', username = single_user.username ) }}">
              {{ single_user.username }}
            </a>
          </stream>
        {% endfor %}
      </div>

    {% endif %}

  </div>

{% endblock %}

app/templates/ticket/ticket_submit.html
{% extends "base_DXcator.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}

<style>
  div.ticket-container {
    font-size: 150%;
  }
  .value {
    font-weight: normal;
    font-family: monospace;
    font-size: 80%;
  }
  stream.key {
    font-weight: bold;
  }
  #larger {
    font-size: 100%;
    font-family: monospace;
  }
</style>

  <div class="ticket-container" style="margin-top: 5%;">

    <stream class="key">Author:</stream> <stream class="value">{{ current_user.username }}</stream>
    <br>
    <br>

    <form class="form-inline"  method="POST">
      {{ form.hidden_tag() }}

      {% for error in form.urgency.errors %}
        <span style="color: red;">[{{ error }}]</span>
      {% endfor %}
      <div class="form-group">
        {{ form.urgency.label }}: {{ form.urgency(class="value") }}
      </div>
      <br>
      <br>

      {% for error in form.application.errors %}
        <span style="color: red;">[{{ error }}]</span>
      {% endfor %}
      <div class="form-group">
        {{ form.application.label }}: {{ form.application(class="value") }}
      </div>
      <br>
      <br>

      {% for error in form.argument.errors %}
        <span style="color: red;">[{{ error }}]</span>
      {% endfor %}
      <div class="form-group">
        {{ form.argument.label }}: {{ form.argument(class="value") }}
      </div>
      <br>
      <br>

      {% for error in form.title.errors %}
        <span style="color: red;">[{{ error }}]</span>
      {% endfor %}
      <div class="form-group">
        {{ form.title.label }}<stream style="font-size: 80%;"> (max 250 chars)</stream>: {{ form.title(class="value") }}
      </div>
      <br>
      <br>


      <div class="form-group">
        {{ form.body.label }}:
        <br>
        {{ form.body(cols="60", rows="6", id='larger') }}
      </div>
      <br>
      <br>
      <div class="form-group">
        {{ form.submit(class="btn btn-default") }}
      </div>
    </form>

  </div>

{% endblock %}

app/templates/ticket/user.html
{% extends "base_DXcator.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}

<style>
  th {
    text-align: center;
    font-size: 120%;
    background-color: #dedede;
  }
  h3 {
    margin-left: 1%;
  }
  stream.username {
    color: grey;
    font-size: 80%;
  }
  td {
    font-size: 90%;
    font-family: monospace;
    max-width: 20%;
    overflow-wrap: break-word;
  }
  table {
    table-layout:fixed;
    width:100%;
  }
</style>


  <h1>User: <stream class="username">{{ user.username }}</stream></h1>
  <div style="text-align: center;">
    <a href="{{ url_for('ticket.submit')}}">
    <button class="btn btn-info">Submit your ticket</button>
    </a>
  </div>

  <hr>
  <h3>Tickets:</h3>

  <table class="table table-hover" style="text-align: center;">

    <thead>
      <tr>
        <th>
          author
        </th>
        <th>
          title
        </th>
        <th>
          application
        </th>
        <th>
          topic
        </th>
        <th>
          created on
        </th>
        <th>
          last update
        </th>
      </tr>
    </thead>

    <tbody>
      {% for ticket in tickets %}
      <tr>
        <td>
          <a href="{{ url_for( 'ticket.user', username = ticket.author.username ) }}">
            {{ ticket.author.username }}
          </a>
        <td>
          <a href="{{ url_for( 'ticket.ticket_reply', ticket_ID = ticket.id ) }}" target="_blank">
            {{ ticket.title }}
          </a>
        </td>
        <td>
          {{ ticket_app[ticket.application|string] }}
        </td>
        <td>
          {{ ticket_arg[ticket.argument|string] }}
        </td>
        <td>
          {{ ticket.timestamp.strftime("%m-%d-%Y (%H:%M)") }}
        </td>
        <td>
          {{ ticket.last_modify.strftime("%m-%d-%Y (%H:%M)") }}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>


  <hr>
  <h3>Ticket Followed:</h3>

  <table class="table table-hover" style="text-align: center;">

    <thead>
      <tr>
        <th>
          author
        </th>
        <th>
          title
        </th>
        <th>
          application
        </th>
        <th>
          topic
        </th>
        <th>
          created on
        </th>
        <th>
          last update
        </th>
      </tr>
    </thead>

    <tbody>
      {% for ticket in tickets_followed %}
      <tr>
        <td>
          <a href="{{ url_for( 'ticket.user', username = ticket.author.username ) }}">
            {{ ticket.author.username }}
          </a>
        <td>
          <a href="{{ url_for( 'ticket.ticket_reply', ticket_ID = ticket.id ) }}" target="_blank">
            {{ ticket.title }}
          </a>
        </td>
        <td>
          {{ ticket_app[ticket.application|string] }}
        </td>
        <td>
          {{ ticket_arg[ticket.argument|string] }}
        </td>
        <td>
          {{ ticket.timestamp.strftime("%m-%d-%Y (%H:%M)") }}
        </td>
        <td>
          {{ ticket.last_modify.strftime("%m-%d-%Y (%H:%M)") }}
        </td>
      </tr>
      {% endfor %}
    </tbody>


  </table>


  <hr>
  <h3>Ticket Updates:</h3>

  <table class="table table-hover" style="text-align: center;">

    <thead>
      <tr>
        <th>
          author
        </th>
        <th>
          title
        </th>
        <th>
          application
        </th>
        <th>
          topic
        </th>
        <th>
          created on
        </th>
      </tr>
    </thead>

    <tbody>
      {% for ticket in ticket_replies %}
      <tr>
        <td>
          <a href="{{ url_for( 'ticket.user', username = ticket.replier.username ) }}">
            {{ ticket.replier.username }}
          </a>
        <td>
          <a href="{{ url_for( 'ticket.ticket_reply', ticket_ID = ticket.original.id ) }}" target="_blank">
            {{ ticket.original.title }}
          </a>
        </td>
        <td>
          {{ ticket_app[ticket.original.application|string] }}
        </td>
        <td>
          {{ ticket_arg[ticket.original.argument|string] }}
        </td>
        <td>
          {{ ticket.timestamp.strftime("%m-%d-%Y (%H:%M)") }}
        </td>
      </tr>
      {% endfor %}
    </tbody>


  </table>

{% endblock %}